name: Build, Push and Deploy Docker Image
run-name: Build, Push and Deploy Image
on: 
  push:
    branches:
      - main
env:
  IMAGE_NAME: "${{ secrets.zezen24 }}/2048-alzena"
  DOCKER_USER: "${{ secrets.zezen24 }}"
jobs:
  build-push-image:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      - name: List Image
        run: docker images
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.zezen24 }}
          password: ${{ secrets.DOCKER_alzena24082009}}
      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy-2048:
    needs: build-push-image
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: stop and remove existing container
        run: docker compose down --rmi all
      - name: start container
        run: docker compose up -d

